// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjX1d-azUOBRdAkVQIMMxfaQ9xl0C6Glw',
    appId: '1:302622426801:web:57412744a02113a052c490',
    messagingSenderId: '302622426801',
    projectId: 'login-35721',
    authDomain: 'login-35721.firebaseapp.com',
    storageBucket: 'login-35721.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOT6W2cFTo_tVVR5T3ab1vV3opA83BMZc',
    appId: '1:302622426801:android:f35d26d80d9575cf52c490',
    messagingSenderId: '302622426801',
    projectId: 'login-35721',
    storageBucket: 'login-35721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8Yqy0VxXmJph4yLQkiGVmbVKWWMIDzo',
    appId: '1:302622426801:ios:b7608b9e870021b452c490',
    messagingSenderId: '302622426801',
    projectId: 'login-35721',
    storageBucket: 'login-35721.firebasestorage.app',
    iosBundleId: 'com.example.puebaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8Yqy0VxXmJph4yLQkiGVmbVKWWMIDzo',
    appId: '1:302622426801:ios:b7608b9e870021b452c490',
    messagingSenderId: '302622426801',
    projectId: 'login-35721',
    storageBucket: 'login-35721.firebasestorage.app',
    iosBundleId: 'com.example.puebaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjX1d-azUOBRdAkVQIMMxfaQ9xl0C6Glw',
    appId: '1:302622426801:web:ad4183f1f2ea2c5752c490',
    messagingSenderId: '302622426801',
    projectId: 'login-35721',
    authDomain: 'login-35721.firebaseapp.com',
    storageBucket: 'login-35721.firebasestorage.app',
  );
}
